"""test_live_gemini.py — ONE live smoke test against the REAL Gemini gateway
(HEALTH_AGENT_PLAN.md §9, §10 step 7), gated `UW_RUN_LIVE=1` exactly like the 3
existing live tests in underwriting/tests/test_grounding.py.

Uses Gemini specifically (not the shared .env LLM_MODEL, which points at the company
gpt-4o gateway) — reconfigures DSPy's LM in-process for this one test only, via the
same `configure_lm()` underwriting.judge already uses, so no other test or the shared
.env is disturbed. Requires GEMINI_API_KEY in .env (already present and live-verified,
HEALTH_AGENT_PLAN.md §2.1).

Run: UW_RUN_LIVE=1 python -m pytest journey/health_agent/tests/test_live_gemini.py -v -s
"""
from __future__ import annotations

import os

import pytest

from journey.health_agent import engine as E

pytestmark = pytest.mark.skipif(
    os.environ.get("UW_RUN_LIVE", "").strip().lower() not in ("1", "true", "yes")
    or not os.environ.get("GEMINI_API_KEY"),
    reason="opt-in live test: set UW_RUN_LIVE=1 and GEMINI_API_KEY to run",
)


@pytest.fixture(autouse=True)
def _use_gemini():
    """Reconfigure DSPy's LM to Gemini for this test only. Restores whatever was
    configured before (the shared .env gpt-4o gateway) afterward, so this test can't
    leak its model choice into any other test that happens to run in the same process."""
    from underwriting.judge import configure_lm

    prev_model = os.environ.get("LLM_MODEL")
    prev_base = os.environ.get("LLM_BASE_URL")
    os.environ["LLM_MODEL"] = os.environ.get("PRESCRIPTION_OCR_MODEL", "gemini/gemini-2.5-flash")
    os.environ.pop("LLM_BASE_URL", None)  # Gemini goes direct, not through the company gateway
    configure_lm(eval_mode=False)
    yield
    if prev_model is not None:
        os.environ["LLM_MODEL"] = prev_model
    else:
        os.environ.pop("LLM_MODEL", None)
    if prev_base is not None:
        os.environ["LLM_BASE_URL"] = prev_base
    configure_lm(eval_mode=False)


def test_live_triage_flags_cardiac_and_diabetes_from_paulson_abha():
    """Paulson's ABHA record (underwriting/mock_abha.py) has structured evidence for
    BOTH diabetes (E11.9) and cardiac (I25.10) — a real triage call against real Gemini
    must flag both buckets from the actual evidence, not a canned/fake response."""
    from underwriting.mock_abha import records_for

    record = records_for(pan="BHYPM4927Q")
    flagged = E.run_triage(abha_facts=record)

    print("\n[live triage] flagged:", flagged)
    buckets = {f["bucket"] for f in flagged}
    assert "diabetes" in buckets, f"expected diabetes flagged from E11.9, got {flagged}"
    assert "cardiac" in buckets, f"expected cardiac flagged from I25.10, got {flagged}"
    for f in flagged:
        assert f["trigger_fact"], "a real triage call must cite a supporting fact"


def test_live_conversation_thread_closes_with_a_real_status():
    """One real, live conversation for the cardiac bucket: ask -> answer -> ask ->
    answer -> close, using genuine (scripted but realistic) applicant answers. Proves
    the actual prompt text (not the offline fake-LM stand-in) produces sensible,
    plain-language questions and a real structured summary."""
    answers = iter([
        "I was diagnosed with a heart issue back in 2019.",
        "It's still ongoing, I take medication for it daily.",
        "Atorvastatin, once a day at night.",
        "No hospitalization, it's been stable and well managed.",
    ])
    questions_seen: list[str] = []

    def answer_cb(question: str) -> str:
        questions_seen.append(question)
        print(f"\n[live chat] Q: {question}")
        a = next(answers, "That's all I know.")
        print(f"[live chat] A: {a}")
        return a

    result = E.run_condition_thread("cardiac", "abha.icd_codes=I25.10", answer_cb)

    print("\n[live chat] ended_reason:", result["ended_reason"])
    print("[live chat] summary:", result["summary"])

    assert result["turns_used"] >= 1
    assert result["summary"]["current_status"] is not None, "a real summarize call should extract SOME status"
    # Plain-language guardrail (§11 item 6b): no raw clinical jargon leaking into a
    # question actually generated by the real model.
    jargon = ["onset", "severity marker", "comorbid", "etiology", "asymptomatic"]
    for q in questions_seen:
        for term in jargon:
            assert term not in q.lower(), f"jargon '{term}' leaked into live question: {q!r}"
